### ISSUE TITLE
Missing Shims

### ISSUE THREAD

**Issue by dcuddeback** [HashNuke/asdf-ruby#2]
I installed `asdf` and `asdf-ruby`, then install Ruby 2.1.5, but there are no shims in `~/.asdf/shims`:

```
git clone https://github.com/HashNuke/asdf.git ~/.asdf
echo '. $HOME/.asdf/asdf.sh' >> ~/.bashrc
```

reload my shell...

```
asdf plugin-add ruby https://github.com/HashNuke/asdf-ruby.git
asdf install ruby 2.15
```

`asdf` recognizes the correct version from `.tool-versions`, but I end up getting the system Ruby:

```
$ asdf which ruby
2.1.5
$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

There are no shims in `~/.asdf/shims`:

```
$ ls -Alh ~/.asdf/shims/
# no output
```

**Comment by dcuddeback** [comment]
I tried `reshim` with no success:

```
$ asdf reshim ruby 2.1.5
$ ls -Alh ~/.asdf/shims/
# no output
```

**Comment by HashNuke** [comment]
@dcuddeback Thank you for reporting this David ~!
It was a bug in asdf. I've fixed it.

To get the fix:
```
cd ~/.asdf
git pull origin master
```

Please re-open this issue incase you still have the same problem.
