### ISSUE TITLE
Ruby 2.1.6

### ISSUE THREAD

**Issue by rstacruz** [HashNuke/asdf-ruby#7]
Any reason that some ruby versions are missing?

**Comment by HashNuke** [comment]
@rstacruz we maintain a static file-based list of ruby versions just for reference. But if you know a version that's not yet in the list then just go ahead and run the install command. It'll work.

**Comment by HashNuke** [comment]
@rstacruz Thanks for reporting. Added 2.1.6
https://github.com/HashNuke/asdf-ruby/commit/24cff313ebfc1d716d99334045025c5b42388659
